/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uneti.cntt.ttltm.labtwo.exercisetwo;

import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Vector;
import java.util.stream.Stream;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phaml
 */
public class ProductManagementForm extends javax.swing.JFrame {

    Vector vtHeader = new Vector();
    Vector vtData = new Vector();
    List<Product> lstProducts = new Vector<>();
    static int id;

    /**
     * Creates new form ProductManagementForm
     */
    public ProductManagementForm() {
        initComponents();
        txtMaHangHoa.disable();
        vtHeader.add("Ma hang hoa");
        vtHeader.add("Ten hang hoa");
        vtHeader.add("Gia ban");
        vtHeader.add("So luong");
        tblProduct.setModel(new DefaultTableModel(vtData, vtHeader));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void clearData() {
        txtGiaSanPham.setText("");
        txtTenHangHoa.setText("");
        spnSoLuong.setValue(0);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMaHangHoa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenHangHoa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtGiaSanPham = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProduct);

        jLabel1.setText("Mã hàng hóa");

        jLabel2.setText("Tên hàng hóa");

        jLabel3.setText("Số lượng");

        jLabel4.setText("Giá sản phẩm");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Quản lý sản phẩm");

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd1.setText("Thêm mới");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnSort.setText("Sắp xếp giảm dần");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnAdd1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMaHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSort)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGiaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd1)
                    .addComponent(btnSearch)
                    .addComponent(btnSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        Product p = new Product("HH" + ++id, txtTenHangHoa.getText(), Float.parseFloat(txtGiaSanPham.getText()), (Integer) spnSoLuong.getValue());
        lstProducts.add(p);
        Vector vtRow = new Vector();
        vtRow.add(p.getMaHH());
        vtRow.add(p.getTenHH());
        vtRow.add(p.getGiaSP());
        vtRow.add(p.getSoLuong());
        vtData.add(vtRow);
        tblProduct.setModel(new DefaultTableModel(vtData, vtHeader));
        clearData();
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        // TODO add your handling code here:
        Collections.sort(lstProducts, new Comparator<Product>() {
            @Override
            public int compare(Product o1, Product o2) {
                if (o1.getGiaSP() < o2.getGiaSP()) {
                    return 1;
                } else {
                    if (o1.getGiaSP() == o2.getGiaSP()) {
                        return 0;
                    } else {
                        return -1;
                    }
                }
            }

        });
        for (Product p : lstProducts) {
            System.out.println(p.toString());
        }

        vtData.clear();
        tblProduct.setModel(new DefaultTableModel(vtData, vtHeader));
        for (Product product : lstProducts) {
            Vector vtRow = new Vector();
            vtRow.add(product.getMaHH());
            vtRow.add(product.getTenHH());
            vtRow.add(product.getGiaSP());
            vtRow.add(product.getSoLuong());
            vtData.add(vtRow);
            tblProduct.setModel(new DefaultTableModel(vtData, vtHeader));
        }
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String productName = txtSearch.getText();
        vtData.clear();
        tblProduct.setModel(new DefaultTableModel(vtData, vtHeader));
        for (Product product : lstProducts) {
            if (product.getTenHH().equalsIgnoreCase(productName)) {
                Vector vtRow = new Vector();
                vtRow.add(product.getMaHH());
                vtRow.add(product.getTenHH());
                vtRow.add(product.getGiaSP());
                vtRow.add(product.getSoLuong());
                vtData.add(vtRow);
                tblProduct.setModel(new DefaultTableModel(vtData, vtHeader));
            }
            if(productName == ""){
                Vector vtRow = new Vector();
                vtRow.add(product.getMaHH());
                vtRow.add(product.getTenHH());
                vtRow.add(product.getGiaSP());
                vtRow.add(product.getSoLuong());
                vtData.add(vtRow);
                tblProduct.setModel(new DefaultTableModel(vtData, vtHeader));
            }
            Comparator<Product> comparator = Comparator.comparing(Product::getGiaSP);
            if (productName.equals("MAX")) {
                Product lst = lstProducts.stream().max(comparator).get();
                if (lst != null) {
                    Vector vtRow = new Vector();
                    vtRow.add(product.getMaHH());
                    vtRow.add(product.getTenHH());
                    vtRow.add(product.getGiaSP());
                    vtRow.add(product.getSoLuong());
                    vtData.add(vtRow);
                    tblProduct.setModel(new DefaultTableModel(vtData, vtHeader));
                }
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtGiaSanPham;
    private javax.swing.JTextField txtMaHangHoa;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenHangHoa;
    // End of variables declaration//GEN-END:variables
}
